// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: plants.proto

package plants_service_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddPlantRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *AddPlantRequest) Reset() {
	*x = AddPlantRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plants_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPlantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPlantRequest) ProtoMessage() {}

func (x *AddPlantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plants_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPlantRequest.ProtoReflect.Descriptor instead.
func (*AddPlantRequest) Descriptor() ([]byte, []int) {
	return file_plants_proto_rawDescGZIP(), []int{0}
}

func (x *AddPlantRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type AddPlantResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data  []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error []byte `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *AddPlantResponse) Reset() {
	*x = AddPlantResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plants_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPlantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPlantResponse) ProtoMessage() {}

func (x *AddPlantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plants_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPlantResponse.ProtoReflect.Descriptor instead.
func (*AddPlantResponse) Descriptor() ([]byte, []int) {
	return file_plants_proto_rawDescGZIP(), []int{1}
}

func (x *AddPlantResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AddPlantResponse) GetError() []byte {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetPlantsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetPlantsRequest) Reset() {
	*x = GetPlantsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plants_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlantsRequest) ProtoMessage() {}

func (x *GetPlantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plants_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlantsRequest.ProtoReflect.Descriptor instead.
func (*GetPlantsRequest) Descriptor() ([]byte, []int) {
	return file_plants_proto_rawDescGZIP(), []int{2}
}

func (x *GetPlantsRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetPlantsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data  []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error []byte `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetPlantsResponse) Reset() {
	*x = GetPlantsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plants_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlantsResponse) ProtoMessage() {}

func (x *GetPlantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plants_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlantsResponse.ProtoReflect.Descriptor instead.
func (*GetPlantsResponse) Descriptor() ([]byte, []int) {
	return file_plants_proto_rawDescGZIP(), []int{3}
}

func (x *GetPlantsResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetPlantsResponse) GetError() []byte {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetPlantByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetPlantByIdRequest) Reset() {
	*x = GetPlantByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plants_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlantByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlantByIdRequest) ProtoMessage() {}

func (x *GetPlantByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plants_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlantByIdRequest.ProtoReflect.Descriptor instead.
func (*GetPlantByIdRequest) Descriptor() ([]byte, []int) {
	return file_plants_proto_rawDescGZIP(), []int{4}
}

func (x *GetPlantByIdRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetPlantByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data  []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error []byte `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetPlantByIdResponse) Reset() {
	*x = GetPlantByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plants_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlantByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlantByIdResponse) ProtoMessage() {}

func (x *GetPlantByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plants_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlantByIdResponse.ProtoReflect.Descriptor instead.
func (*GetPlantByIdResponse) Descriptor() ([]byte, []int) {
	return file_plants_proto_rawDescGZIP(), []int{5}
}

func (x *GetPlantByIdResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetPlantByIdResponse) GetError() []byte {
	if x != nil {
		return x.Error
	}
	return nil
}

type UpdatePlantByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UpdatePlantByIdRequest) Reset() {
	*x = UpdatePlantByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plants_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePlantByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlantByIdRequest) ProtoMessage() {}

func (x *UpdatePlantByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plants_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlantByIdRequest.ProtoReflect.Descriptor instead.
func (*UpdatePlantByIdRequest) Descriptor() ([]byte, []int) {
	return file_plants_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePlantByIdRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdatePlantByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data  []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error []byte `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *UpdatePlantByIdResponse) Reset() {
	*x = UpdatePlantByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plants_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePlantByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlantByIdResponse) ProtoMessage() {}

func (x *UpdatePlantByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plants_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlantByIdResponse.ProtoReflect.Descriptor instead.
func (*UpdatePlantByIdResponse) Descriptor() ([]byte, []int) {
	return file_plants_proto_rawDescGZIP(), []int{7}
}

func (x *UpdatePlantByIdResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UpdatePlantByIdResponse) GetError() []byte {
	if x != nil {
		return x.Error
	}
	return nil
}

type DeletePlantByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DeletePlantByIdRequest) Reset() {
	*x = DeletePlantByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plants_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePlantByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlantByIdRequest) ProtoMessage() {}

func (x *DeletePlantByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plants_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlantByIdRequest.ProtoReflect.Descriptor instead.
func (*DeletePlantByIdRequest) Descriptor() ([]byte, []int) {
	return file_plants_proto_rawDescGZIP(), []int{8}
}

func (x *DeletePlantByIdRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeletePlantByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data  []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error []byte `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *DeletePlantByIdResponse) Reset() {
	*x = DeletePlantByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plants_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePlantByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlantByIdResponse) ProtoMessage() {}

func (x *DeletePlantByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plants_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlantByIdResponse.ProtoReflect.Descriptor instead.
func (*DeletePlantByIdResponse) Descriptor() ([]byte, []int) {
	return file_plants_proto_rawDescGZIP(), []int{9}
}

func (x *DeletePlantByIdResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DeletePlantByIdResponse) GetError() []byte {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_plants_proto protoreflect.FileDescriptor

var file_plants_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x25,
	0x0a, 0x0f, 0x41, 0x64, 0x64, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3c, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x50, 0x6c, 0x61, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x22, 0x26, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3d, 0x0a, 0x11, 0x47,
	0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x29, 0x0a, 0x13, 0x47, 0x65,
	0x74, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x40, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e,
	0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x2c, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x43, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50,
	0x6c, 0x61, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x2c, 0x0a, 0x16, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x43, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0xdb, 0x02,
	0x0a, 0x0d, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x12,
	0x35, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x63, 0x12,
	0x10, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x11, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61,
	0x6e, 0x74, 0x73, 0x50, 0x72, 0x6f, 0x63, 0x12, 0x11, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x47, 0x65, 0x74,
	0x50, 0x6c, 0x61, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x41, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x64,
	0x50, 0x72, 0x6f, 0x63, 0x12, 0x14, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x42,
	0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x47, 0x65, 0x74,
	0x50, 0x6c, 0x61, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61,
	0x6e, 0x74, 0x42, 0x79, 0x49, 0x64, 0x50, 0x72, 0x6f, 0x63, 0x12, 0x17, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x6e,
	0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x4a, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x42, 0x79,
	0x49, 0x64, 0x50, 0x72, 0x6f, 0x63, 0x12, 0x17, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50,
	0x6c, 0x61, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x18, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x42, 0x79, 0x49,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x16, 0x5a, 0x14, 0x2f,
	0x70, 0x6c, 0x61, 0x6e, 0x74, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x67,
	0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_plants_proto_rawDescOnce sync.Once
	file_plants_proto_rawDescData = file_plants_proto_rawDesc
)

func file_plants_proto_rawDescGZIP() []byte {
	file_plants_proto_rawDescOnce.Do(func() {
		file_plants_proto_rawDescData = protoimpl.X.CompressGZIP(file_plants_proto_rawDescData)
	})
	return file_plants_proto_rawDescData
}

var file_plants_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_plants_proto_goTypes = []interface{}{
	(*AddPlantRequest)(nil),         // 0: AddPlantRequest
	(*AddPlantResponse)(nil),        // 1: AddPlantResponse
	(*GetPlantsRequest)(nil),        // 2: GetPlantsRequest
	(*GetPlantsResponse)(nil),       // 3: GetPlantsResponse
	(*GetPlantByIdRequest)(nil),     // 4: GetPlantByIdRequest
	(*GetPlantByIdResponse)(nil),    // 5: GetPlantByIdResponse
	(*UpdatePlantByIdRequest)(nil),  // 6: UpdatePlantByIdRequest
	(*UpdatePlantByIdResponse)(nil), // 7: UpdatePlantByIdResponse
	(*DeletePlantByIdRequest)(nil),  // 8: DeletePlantByIdRequest
	(*DeletePlantByIdResponse)(nil), // 9: DeletePlantByIdResponse
}
var file_plants_proto_depIdxs = []int32{
	0, // 0: PlantResolver.AddPlantProc:input_type -> AddPlantRequest
	2, // 1: PlantResolver.GetPlantsProc:input_type -> GetPlantsRequest
	4, // 2: PlantResolver.GetPlantByIdProc:input_type -> GetPlantByIdRequest
	6, // 3: PlantResolver.UpdatePlantByIdProc:input_type -> UpdatePlantByIdRequest
	8, // 4: PlantResolver.DeletePlantByIdProc:input_type -> DeletePlantByIdRequest
	1, // 5: PlantResolver.AddPlantProc:output_type -> AddPlantResponse
	3, // 6: PlantResolver.GetPlantsProc:output_type -> GetPlantsResponse
	5, // 7: PlantResolver.GetPlantByIdProc:output_type -> GetPlantByIdResponse
	7, // 8: PlantResolver.UpdatePlantByIdProc:output_type -> UpdatePlantByIdResponse
	9, // 9: PlantResolver.DeletePlantByIdProc:output_type -> DeletePlantByIdResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_plants_proto_init() }
func file_plants_proto_init() {
	if File_plants_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_plants_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPlantRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plants_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPlantResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plants_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlantsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plants_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlantsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plants_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlantByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plants_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlantByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plants_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePlantByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plants_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePlantByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plants_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePlantByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plants_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePlantByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_plants_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plants_proto_goTypes,
		DependencyIndexes: file_plants_proto_depIdxs,
		MessageInfos:      file_plants_proto_msgTypes,
	}.Build()
	File_plants_proto = out.File
	file_plants_proto_rawDesc = nil
	file_plants_proto_goTypes = nil
	file_plants_proto_depIdxs = nil
}
